import '@servicenow/sdk/global'
import { BusinessRule, RestApi, ScheduledScript, ScriptInclude, UiAction } from '@servicenow/sdk/core'
import { topoOperator, topoWorkerEndpoint } from './security.now'

ScriptInclude({
    $id: Now.ID['script-include-topo-control-plane'],
    name: 'TopoControlPlane',
    apiName: 'x_664635_topo.TopoControlPlane',
    description: 'Lease, attempt-bound credential, result, schedule, run-summary, and retention state machine for stateless Topo workers.',
    script: Now.include('../../scripts/TopoControlPlane.js'),
    active: true,
    clientCallable: false,
    mobileCallable: false,
    sandboxCallable: false,
    accessibleFrom: 'package_private',
})

ScriptInclude({
    $id: Now.ID['script-include-topo-observation-mapper'],
    name: 'TopoObservationMapper',
    apiName: 'x_664635_topo.TopoObservationMapper',
    description: 'Reviewed Slice A mapping for computer, network adapter, and Owns::Owned by observations only.',
    script: Now.include('../../scripts/TopoObservationMapper.js'),
    active: true,
    clientCallable: false,
    mobileCallable: false,
    sandboxCallable: false,
    accessibleFrom: 'package_private',
})

ScriptInclude({
    $id: Now.ID['script-include-topo-ire-processor'],
    name: 'TopoIREProcessor',
    apiName: 'x_664635_topo.TopoIREProcessor',
    description: 'Performs IRE queryEnhanced preflight and createOrUpdate apply for reviewed Topo payloads.',
    script: Now.include('../../scripts/TopoIREProcessor.js'),
    active: true,
    clientCallable: false,
    mobileCallable: false,
    sandboxCallable: false,
    accessibleFrom: 'package_private',
})

RestApi({
    $id: Now.ID['rest-api-topo-worker-v1'],
    name: 'Topo Worker API',
    serviceId: 'tasks',
    shortDescription: 'Fixed outbound API for stateless Topo workers executing reviewed local.v1 and ssh_linux.v1 operations.',
    active: true,
    consumes: 'application/json',
    produces: 'application/json',
    enforceAcl: [topoWorkerEndpoint],
    versions: [
        {
            $id: Now.ID['rest-api-topo-worker-version-v1'],
            version: 1,
            isDefault: true,
            active: true,
            deprecated: false,
            shortDescription: 'Fixed versioned Topo worker contract with attempt-bound Password2 retrieval.',
        },
    ],
    routes: [
        {
            $id: Now.ID['rest-route-register-worker'],
            name: 'Register worker',
            version: 1,
            method: 'POST',
            path: '/workers/register',
            script: Now.include('../../scripts/register_worker.js'),
            authentication: true,
            authorization: true,
            internalRole: false,
            enforceAcl: [topoWorkerEndpoint],
            consumes: 'application/json',
            produces: 'application/json',
            active: true,
        },
        {
            $id: Now.ID['rest-route-worker-heartbeat'],
            name: 'Worker heartbeat',
            version: 1,
            method: 'POST',
            path: '/workers/heartbeat',
            script: Now.include('../../scripts/worker_heartbeat.js'),
            authentication: true,
            authorization: true,
            internalRole: false,
            enforceAcl: [topoWorkerEndpoint],
            consumes: 'application/json',
            produces: 'application/json',
            active: true,
        },
        {
            $id: Now.ID['rest-route-claim-task'],
            name: 'Claim task',
            version: 1,
            method: 'POST',
            path: '/claim',
            script: Now.include('../../scripts/claim_task.js'),
            authentication: true,
            authorization: true,
            internalRole: false,
            enforceAcl: [topoWorkerEndpoint],
            consumes: 'application/json',
            produces: 'application/json',
            active: true,
        },
        {
            $id: Now.ID['rest-route-renew-task'],
            name: 'Renew task lease',
            version: 1,
            method: 'POST',
            path: '/{id}/renew',
            script: Now.include('../../scripts/renew_task.js'),
            authentication: true,
            authorization: true,
            internalRole: false,
            enforceAcl: [topoWorkerEndpoint],
            consumes: 'application/json',
            produces: 'application/json',
            active: true,
        },
        {
            $id: Now.ID['rest-route-task-credential'],
            name: 'Retrieve attempt-bound task credential',
            version: 1,
            method: 'POST',
            path: '/{id}/credential',
            script: Now.include('../../scripts/credential_task.js'),
            authentication: true,
            authorization: true,
            internalRole: false,
            enforceAcl: [topoWorkerEndpoint],
            consumes: 'application/json',
            produces: 'application/json',
            active: true,
        },
        {
            $id: Now.ID['rest-route-ingest-result'],
            name: 'Ingest result chunk',
            version: 1,
            method: 'POST',
            path: '/{id}/results',
            script: Now.include('../../scripts/ingest_result.js'),
            authentication: true,
            authorization: true,
            internalRole: false,
            enforceAcl: [topoWorkerEndpoint],
            consumes: 'application/json',
            produces: 'application/json',
            active: true,
        },
        {
            $id: Now.ID['rest-route-complete-task'],
            name: 'Complete task',
            version: 1,
            method: 'POST',
            path: '/{id}/complete',
            script: Now.include('../../scripts/complete_task.js'),
            authentication: true,
            authorization: true,
            internalRole: false,
            enforceAcl: [topoWorkerEndpoint],
            consumes: 'application/json',
            produces: 'application/json',
            active: true,
        },
    ],
})

BusinessRule({
    $id: Now.ID['business-rule-validate-profile'],
    name: 'Validate immutable Topo profile revision',
    table: 'x_664635_topo_profile',
    when: 'before',
    action: ['insert', 'update'],
    order: 100,
    active: true,
    access: 'package_private',
    description: 'Validates reviewed local.v1 and ssh_linux.v1 profile revisions and rejects mutations after use.',
    script: Now.include('../../scripts/validate_profile.js'),
})

BusinessRule({
    $id: Now.ID['business-rule-validate-ssh-credential'],
    name: 'Validate Topo SSH Password2 credential',
    table: 'x_664635_topo_ssh_credential',
    when: 'before',
    action: ['insert', 'update'],
    order: 100,
    active: true,
    access: 'package_private',
    description: 'Validates bounded SSH credential metadata without exposing or auditing the Password2 value.',
    script: Now.include('../../scripts/validate_ssh_credential.js'),
})

BusinessRule({
    $id: Now.ID['business-rule-validate-credential-binding'],
    name: 'Validate immutable Topo credential binding revision',
    table: 'x_664635_topo_credential_binding',
    when: 'before',
    action: ['insert', 'update'],
    order: 100,
    active: true,
    access: 'package_private',
    description: 'Binds one Password2 credential to one reviewed profile revision and one target scope.',
    script: Now.include('../../scripts/validate_credential_binding.js'),
})

BusinessRule({
    $id: Now.ID['business-rule-validate-target-scope'],
    name: 'Validate immutable Topo target scope',
    table: 'x_664635_topo_target_scope',
    when: 'before',
    action: ['insert', 'update'],
    order: 100,
    active: true,
    access: 'package_private',
    description: 'Canonicalizes bounded IPv4 CIDRs and compiles deterministic non-overlapping partition metadata.',
    script: Now.include('../../scripts/validate_target_scope.js'),
})

UiAction({
    $id: Now.ID['ui-action-profile-run-now'],
    name: 'Run now',
    actionName: 'x_664635_topo_run_now',
    table: 'x_664635_topo_profile',
    active: true,
    form: { showButton: true, showLink: false, showContextMenu: true, style: 'primary' },
    showInsert: false,
    showUpdate: true,
    condition: 'current.u_active == true',
    script: Now.include('../../scripts/run_now.js'),
    roles: [topoOperator],
    order: 100,
    hint: 'Create a durable ServiceNow-owned run and reviewed ready task partitions.',
})

UiAction({
    $id: Now.ID['ui-action-run-cancel'],
    name: 'Cancel run',
    actionName: 'x_664635_topo_cancel_run',
    table: 'x_664635_topo_run',
    active: true,
    form: { showButton: true, showLink: false, showContextMenu: true, style: 'destructive' },
    showInsert: false,
    showUpdate: true,
    condition: "current.u_state == 'ready' || current.u_state == 'running' || current.u_state == 'cancelling'",
    script: Now.include('../../scripts/cancel_run.js'),
    roles: [topoOperator],
    order: 110,
    hint: 'Cooperatively cancel ready and running Topo task partitions.',
})

ScheduledScript({
    $id: Now.ID['scheduled-script-enqueue-due-schedules'],
    name: 'Topo enqueue due schedules',
    active: true,
    frequency: 'periodically',
    executionInterval: { minutes: 1 },
    script: Now.include('../../scripts/enqueue_due_schedules.js'),
})

ScheduledScript({
    $id: Now.ID['scheduled-script-maintenance'],
    name: 'Topo expire leases and retain results',
    active: true,
    frequency: 'periodically',
    executionInterval: { minutes: 5 },
    script: Now.include('../../scripts/maintenance.js'),
})
