import '@servicenow/sdk/global'
import {
    BooleanColumn,
    DateTimeColumn,
    IntegerColumn,
    Password2Column,
    ReferenceColumn,
    StringColumn,
    Table,
} from '@servicenow/sdk/core'

export const x_664635_topo_worker_pool = Table({
    accessibleFrom: 'package_private',
    callerAccess: 'restricted',
    allowWebServiceAccess: false,
    allowNewFields: false,
    allowUiActions: false,
    allowClientScripts: false,
    audit: true,
    extensible: false,
    textIndex: false,
    name: 'x_664635_topo_worker_pool',
    label: 'Topo Worker Pool',
    display: 'u_name',
    actions: ['read', 'create', 'update', 'delete'],
    schema: {
        u_pool_id: StringColumn({ label: 'Pool ID', maxLength: 128, mandatory: true }),
        u_name: StringColumn({ label: 'Name', maxLength: 255, mandatory: true }),
        u_site_id: StringColumn({ label: 'Site ID', maxLength: 128, mandatory: true }),
        u_service_user: ReferenceColumn({ label: 'Service user', referenceTable: 'sys_user', mandatory: true }),
        u_active: BooleanColumn({ label: 'Active', mandatory: true, default: true }),
        u_lease_seconds: IntegerColumn({ label: 'Lease seconds', mandatory: true, default: 120 }),
        u_max_task_seconds: IntegerColumn({ label: 'Maximum task seconds', mandatory: true, default: 900 }),
        u_max_leases: IntegerColumn({ label: 'Maximum leases', mandatory: true, default: 32 }),
    },
    index: [
        { name: 'pool_id_unique', unique: true, element: 'u_pool_id' },
        { name: 'pool_user_unique', unique: true, element: ['u_service_user', 'u_pool_id'] },
    ],
})

export const x_664635_topo_worker = Table({
    accessibleFrom: 'package_private',
    callerAccess: 'restricted',
    allowWebServiceAccess: false,
    allowNewFields: false,
    allowUiActions: false,
    allowClientScripts: false,
    audit: true,
    extensible: false,
    textIndex: false,
    name: 'x_664635_topo_worker',
    label: 'Topo Worker',
    display: 'u_worker_id',
    actions: ['read', 'delete'],
    schema: {
        u_worker_id: StringColumn({ label: 'Worker ID', maxLength: 128, mandatory: true }),
        u_boot_id: StringColumn({ label: 'Boot ID', maxLength: 128, mandatory: true }),
        u_pool: ReferenceColumn({ label: 'Worker pool', referenceTable: 'x_664635_topo_worker_pool', mandatory: true }),
        u_site_id: StringColumn({ label: 'Site ID', maxLength: 128, mandatory: true }),
        u_version: StringColumn({ label: 'Worker version', maxLength: 64, mandatory: true }),
        u_capabilities: StringColumn({ label: 'Capabilities', maxLength: 255, mandatory: true }),
        u_policy_digest: StringColumn({ label: 'Policy digest', maxLength: 64, mandatory: true }),
        u_max_leases: IntegerColumn({ label: 'Maximum worker leases', mandatory: true, default: 1 }),
        u_current_leases: IntegerColumn({ label: 'Current leases', mandatory: true, default: 0 }),
        u_active: BooleanColumn({ label: 'Active', mandatory: true, default: true }),
        u_started_at: DateTimeColumn({ label: 'Started at', mandatory: true }),
        u_last_heartbeat: DateTimeColumn({ label: 'Last heartbeat', mandatory: true }),
    },
    index: [
        { name: 'worker_id_unique', unique: true, element: 'u_worker_id' },
        { name: 'worker_boot_unique', unique: true, element: ['u_pool', 'u_boot_id'] },
        { name: 'worker_pool_active', unique: false, element: ['u_pool', 'u_active', 'u_last_heartbeat'] },
    ],
})

export const x_664635_topo_target_scope = Table({
    accessibleFrom: 'package_private',
    callerAccess: 'restricted',
    allowWebServiceAccess: false,
    allowNewFields: false,
    allowUiActions: false,
    allowClientScripts: false,
    audit: true,
    extensible: false,
    textIndex: false,
    name: 'x_664635_topo_target_scope',
    label: 'Topo Target Scope',
    display: 'u_name',
    actions: ['read', 'create', 'update', 'delete'],
    schema: {
        u_scope_id: StringColumn({ label: 'Scope ID', maxLength: 128, mandatory: true }),
        u_revision: IntegerColumn({ label: 'Revision', mandatory: true, default: 1 }),
        u_name: StringColumn({ label: 'Name', maxLength: 255, mandatory: true }),
        u_worker_pool: ReferenceColumn({ label: 'Worker pool', referenceTable: 'x_664635_topo_worker_pool', mandatory: true }),
        u_site_id: StringColumn({ label: 'Site ID', maxLength: 128, mandatory: true }),
        u_cidrs: StringColumn({ label: 'Canonical CIDRs', maxLength: 4000, mandatory: true }),
        u_exclusions: StringColumn({ label: 'Canonical exclusions', maxLength: 4000 }),
        u_ipv4_partition_prefix: IntegerColumn({ label: 'IPv4 partition prefix', mandatory: true, default: 24 }),
        u_partition_count: IntegerColumn({ label: 'Planned partitions', mandatory: true, default: 0 }),
        u_plan_digest: StringColumn({ label: 'Partition plan digest', maxLength: 64 }),
        u_active: BooleanColumn({ label: 'Active', mandatory: true, default: true }),
    },
    index: [
        { name: 'target_scope_revision_unique', unique: true, element: ['u_scope_id', 'u_revision'] },
        { name: 'target_scope_pool_active', unique: false, element: ['u_worker_pool', 'u_active'] },
    ],
})

export const x_664635_topo_ssh_credential = Table({
    accessibleFrom: 'package_private',
    callerAccess: 'restricted',
    allowWebServiceAccess: false,
    allowNewFields: false,
    allowUiActions: false,
    allowClientScripts: false,
    audit: true,
    extensible: false,
    textIndex: false,
    name: 'x_664635_topo_ssh_credential',
    label: 'Topo SSH Credential',
    display: 'u_name',
    actions: ['read', 'create', 'update', 'delete'],
    schema: {
        u_credential_id: StringColumn({ label: 'Credential ID', maxLength: 128, mandatory: true }),
        u_name: StringColumn({ label: 'Name', maxLength: 255, mandatory: true }),
        u_username: StringColumn({ label: 'SSH username', maxLength: 64, mandatory: true }),
        u_password: Password2Column({
            label: 'SSH password',
            mandatory: true,
            audit: false,
            attributes: { is_legacy_password2: true, no_data_replicate: true },
        }),
        u_active: BooleanColumn({ label: 'Active', mandatory: true, default: true }),
    },
    index: [{ name: 'ssh_credential_id_unique', unique: true, element: 'u_credential_id' }],
})

export const x_664635_topo_credential_binding = Table({
    accessibleFrom: 'package_private',
    callerAccess: 'restricted',
    allowWebServiceAccess: false,
    allowNewFields: false,
    allowUiActions: false,
    allowClientScripts: false,
    audit: true,
    extensible: false,
    textIndex: false,
    name: 'x_664635_topo_credential_binding',
    label: 'Topo Credential Binding',
    display: 'u_name',
    actions: ['read', 'create', 'update', 'delete'],
    schema: {
        u_binding_id: StringColumn({ label: 'Binding ID', maxLength: 128, mandatory: true }),
        u_revision: IntegerColumn({ label: 'Revision', mandatory: true, default: 1 }),
        u_name: StringColumn({ label: 'Name', maxLength: 255, mandatory: true }),
        u_protocol: StringColumn({
            label: 'Protocol',
            maxLength: 40,
            mandatory: true,
            default: 'ssh_password',
            dropdown: 'dropdown_without_none',
            choices: { ssh_password: { label: 'SSH password' } },
        }),
        u_profile_id: StringColumn({ label: 'Allowed profile ID', maxLength: 128, mandatory: true }),
        u_profile_revision: IntegerColumn({ label: 'Allowed profile revision', mandatory: true }),
        u_target_scope: ReferenceColumn({ label: 'Allowed target scope', referenceTable: 'x_664635_topo_target_scope', mandatory: true }),
        u_credential: ReferenceColumn({ label: 'SSH credential', referenceTable: 'x_664635_topo_ssh_credential', mandatory: true }),
        u_active: BooleanColumn({ label: 'Active', mandatory: true, default: true }),
    },
    index: [
        { name: 'credential_binding_revision_unique', unique: true, element: ['u_binding_id', 'u_revision'] },
        { name: 'credential_binding_profile_scope', unique: false, element: ['u_profile_id', 'u_profile_revision', 'u_target_scope', 'u_active'] },
    ],
})

export const x_664635_topo_credential_access = Table({
    accessibleFrom: 'package_private',
    callerAccess: 'restricted',
    allowWebServiceAccess: false,
    allowNewFields: false,
    allowUiActions: false,
    allowClientScripts: false,
    audit: false,
    extensible: false,
    textIndex: false,
    name: 'x_664635_topo_credential_access',
    label: 'Topo Credential Access',
    display: 'u_event_id',
    actions: ['read', 'delete'],
    schema: {
        u_event_id: StringColumn({ label: 'Event ID', maxLength: 128, mandatory: true }),
        u_task: ReferenceColumn({ label: 'Task', referenceTable: 'x_664635_topo_task' }),
        u_attempt_id: StringColumn({ label: 'Attempt ID', maxLength: 128 }),
        u_worker_id: StringColumn({ label: 'Worker ID', maxLength: 128 }),
        u_binding: ReferenceColumn({ label: 'Credential binding', referenceTable: 'x_664635_topo_credential_binding' }),
        u_outcome: StringColumn({
            label: 'Outcome',
            maxLength: 40,
            mandatory: true,
            dropdown: 'dropdown_without_none',
            choices: { allowed: { label: 'Allowed' }, denied: { label: 'Denied' } },
        }),
        u_reason: StringColumn({ label: 'Reason code', maxLength: 128, mandatory: true }),
        u_accessed_at: DateTimeColumn({ label: 'Accessed at', mandatory: true }),
    },
    index: [
        { name: 'credential_access_event_unique', unique: true, element: 'u_event_id' },
        { name: 'credential_access_task_time', unique: false, element: ['u_task', 'u_accessed_at'] },
    ],
})

export const x_664635_topo_profile = Table({
    accessibleFrom: 'package_private',
    callerAccess: 'restricted',
    allowWebServiceAccess: false,
    allowNewFields: false,
    allowClientScripts: false,
    audit: true,
    extensible: false,
    textIndex: false,
    allowUiActions: true,
    name: 'x_664635_topo_profile',
    label: 'Topo Discovery Profile',
    display: 'u_name',
    actions: ['read', 'create', 'update', 'delete'],
    schema: {
        u_profile_id: StringColumn({ label: 'Profile ID', maxLength: 128, mandatory: true }),
        u_revision: IntegerColumn({ label: 'Revision', mandatory: true, default: 1 }),
        u_name: StringColumn({ label: 'Name', maxLength: 255, mandatory: true }),
        u_operation: StringColumn({
            label: 'Operation',
            maxLength: 40,
            mandatory: true,
            default: 'local.v1',
            dropdown: 'dropdown_without_none',
            choices: {
                'local.v1': { label: 'Local discovery v1' },
                'ssh_linux.v1': { label: 'Linux SSH discovery v1' },
            },
        }),
        u_worker_pool: ReferenceColumn({
            label: 'Worker pool',
            referenceTable: 'x_664635_topo_worker_pool',
            mandatory: true,
        }),
        u_target_scope: ReferenceColumn({ label: 'Target scope', referenceTable: 'x_664635_topo_target_scope' }),
        u_credential_binding: ReferenceColumn({ label: 'Credential binding', referenceTable: 'x_664635_topo_credential_binding' }),
        u_schema_version: StringColumn({ label: 'Schema version', maxLength: 32, mandatory: true, default: 'v1alpha1' }),
        u_active: BooleanColumn({ label: 'Active', mandatory: true, default: true }),
    },
    index: [
        { name: 'profile_revision_unique', unique: true, element: ['u_profile_id', 'u_revision'] },
        { name: 'profile_pool_active', unique: false, element: ['u_worker_pool', 'u_active'] },
    ],
})

export const x_664635_topo_schedule = Table({
    accessibleFrom: 'package_private',
    callerAccess: 'restricted',
    allowWebServiceAccess: false,
    allowNewFields: false,
    allowUiActions: false,
    allowClientScripts: false,
    audit: true,
    extensible: false,
    textIndex: false,
    name: 'x_664635_topo_schedule',
    label: 'Topo Schedule',
    display: 'u_name',
    actions: ['read', 'create', 'update', 'delete'],
    schema: {
        u_schedule_id: StringColumn({ label: 'Schedule ID', maxLength: 128, mandatory: true }),
        u_name: StringColumn({ label: 'Name', maxLength: 255, mandatory: true }),
        u_profile: ReferenceColumn({ label: 'Profile', referenceTable: 'x_664635_topo_profile', mandatory: true }),
        u_interval_minutes: IntegerColumn({ label: 'Interval minutes', mandatory: true, default: 60 }),
        u_next_run: DateTimeColumn({ label: 'Next run', mandatory: true }),
        u_active: BooleanColumn({ label: 'Active', mandatory: true, default: true }),
    },
    index: [
        { name: 'schedule_id_unique', unique: true, element: 'u_schedule_id' },
        { name: 'schedule_due', unique: false, element: ['u_active', 'u_next_run'] },
    ],
})

export const x_664635_topo_run = Table({
    accessibleFrom: 'package_private',
    callerAccess: 'restricted',
    allowWebServiceAccess: false,
    allowNewFields: false,
    allowUiActions: true,
    allowClientScripts: false,
    audit: true,
    extensible: false,
    textIndex: false,
    name: 'x_664635_topo_run',
    label: 'Topo Run',
    display: 'u_run_id',
    actions: ['read', 'delete'],
    schema: {
        u_run_id: StringColumn({ label: 'Run ID', maxLength: 128, mandatory: true }),
        u_profile: ReferenceColumn({ label: 'Profile', referenceTable: 'x_664635_topo_profile', mandatory: true }),
        u_schedule: ReferenceColumn({ label: 'Schedule', referenceTable: 'x_664635_topo_schedule' }),
        u_trigger: StringColumn({
            label: 'Trigger',
            maxLength: 40,
            mandatory: true,
            dropdown: 'dropdown_without_none',
            choices: {
                manual: { label: 'Manual' },
                scheduled: { label: 'Scheduled' },
                retry: { label: 'Retry' },
            },
        }),
        u_state: StringColumn({
            label: 'State',
            maxLength: 40,
            mandatory: true,
            default: 'ready',
            dropdown: 'dropdown_without_none',
            choices: {
                ready: { label: 'Ready' },
                running: { label: 'Running' },
                cancelling: { label: 'Cancelling' },
                complete: { label: 'Complete' },
                failed: { label: 'Failed' },
                cancelled: { label: 'Cancelled' },
            },
        }),
        u_started_at: DateTimeColumn({ label: 'Started at', mandatory: true }),
        u_completed_at: DateTimeColumn({ label: 'Completed at' }),
        u_task_count: IntegerColumn({ label: 'Task count', mandatory: true, default: 0 }),
        u_complete_tasks: IntegerColumn({ label: 'Complete tasks', mandatory: true, default: 0 }),
        u_failed_tasks: IntegerColumn({ label: 'Failed tasks', mandatory: true, default: 0 }),
        u_cancelled_tasks: IntegerColumn({ label: 'Cancelled tasks', mandatory: true, default: 0 }),
        u_attempts: IntegerColumn({ label: 'Attempts', mandatory: true, default: 0 }),
        u_assets: IntegerColumn({ label: 'Assets', mandatory: true, default: 0 }),
        u_relationships: IntegerColumn({ label: 'Relationships', mandatory: true, default: 0 }),
        u_collection_errors: IntegerColumn({ label: 'Collection errors', mandatory: true, default: 0 }),
        u_error: StringColumn({ label: 'Error', maxLength: 4000 }),
    },
    index: [
        { name: 'run_id_unique', unique: true, element: 'u_run_id' },
        { name: 'run_schedule_state', unique: false, element: ['u_schedule', 'u_state'] },
        { name: 'run_profile_state', unique: false, element: ['u_profile', 'u_state'] },
    ],
})

export const x_664635_topo_task = Table({
    accessibleFrom: 'package_private',
    callerAccess: 'restricted',
    allowWebServiceAccess: false,
    allowNewFields: false,
    allowUiActions: false,
    allowClientScripts: false,
    audit: true,
    extensible: false,
    textIndex: false,
    name: 'x_664635_topo_task',
    label: 'Topo Task',
    display: 'u_task_id',
    actions: ['read', 'delete'],
    schema: {
        u_task_id: StringColumn({ label: 'Task ID', maxLength: 128, mandatory: true }),
        u_run: ReferenceColumn({ label: 'Run', referenceTable: 'x_664635_topo_run', mandatory: true }),
        u_worker_pool: ReferenceColumn({
            label: 'Worker pool',
            referenceTable: 'x_664635_topo_worker_pool',
            mandatory: true,
        }),
        u_operation: StringColumn({
            label: 'Operation',
            maxLength: 40,
            mandatory: true,
            default: 'local.v1',
            dropdown: 'dropdown_without_none',
            choices: {
                'local.v1': { label: 'Local discovery v1' },
                'ssh_linux.v1': { label: 'Linux SSH discovery v1' },
            },
        }),
        u_profile_id: StringColumn({ label: 'Profile ID', maxLength: 128, mandatory: true }),
        u_profile_revision: IntegerColumn({ label: 'Profile revision', mandatory: true }),
        u_target_scope: ReferenceColumn({ label: 'Target scope', referenceTable: 'x_664635_topo_target_scope' }),
        u_credential_binding: ReferenceColumn({ label: 'Credential binding', referenceTable: 'x_664635_topo_credential_binding' }),
        u_partition_key: StringColumn({ label: 'Partition key', maxLength: 128 }),
        u_partition_ordinal: IntegerColumn({ label: 'Partition ordinal', mandatory: true, default: 0 }),
        u_partition_count: IntegerColumn({ label: 'Partition count', mandatory: true, default: 1 }),
        u_partition_cidrs: StringColumn({ label: 'Canonical partition CIDRs', maxLength: 4000 }),
        u_state: StringColumn({
            label: 'State',
            maxLength: 40,
            mandatory: true,
            default: 'planned',
            dropdown: 'dropdown_without_none',
            choices: {
                planned: { label: 'Planned' },
                ready: { label: 'Ready' },
                leased: { label: 'Leased' },
                running: { label: 'Running' },
                results_received: { label: 'Results received' },
                ire_processing: { label: 'IRE processing' },
                complete: { label: 'Complete' },
                failed: { label: 'Failed' },
                cancelled: { label: 'Cancelled' },
            },
        }),
        u_attempt_count: IntegerColumn({ label: 'Attempt count', mandatory: true, default: 0 }),
        u_attempt_id: StringColumn({ label: 'Attempt ID', maxLength: 128 }),
        u_lease_worker: ReferenceColumn({ label: 'Lease worker', referenceTable: 'x_664635_topo_worker' }),
        u_lease_boot_id: StringColumn({ label: 'Lease boot ID', maxLength: 128 }),
        u_lease_token_digest: StringColumn({ label: 'Lease token digest', maxLength: 64 }),
        u_pool_lease_slot: StringColumn({ label: 'Pool lease slot', maxLength: 64 }),
        u_worker_lease_slot: StringColumn({ label: 'Worker lease slot', maxLength: 64 }),
        u_lease_expires: DateTimeColumn({ label: 'Lease expires' }),
        u_completion_id: StringColumn({ label: 'Completion ID', maxLength: 128 }),
        u_deadline: DateTimeColumn({ label: 'Deadline', mandatory: true }),
        u_chunk_count: IntegerColumn({ label: 'Chunk count', mandatory: true, default: 0 }),
        u_cancel_requested: BooleanColumn({ label: 'Cancellation requested', mandatory: true, default: false }),
        u_error: StringColumn({ label: 'Error', maxLength: 4000 }),
    },
    index: [
        { name: 'task_id_unique', unique: true, element: 'u_task_id' },
        { name: 'task_claim', unique: false, element: ['u_worker_pool', 'u_state', 'u_partition_ordinal', 'sys_created_on'] },
        { name: 'task_lease_expiry', unique: false, element: ['u_state', 'u_lease_expires'] },
        { name: 'task_run_state', unique: false, element: ['u_run', 'u_state'] },
        { name: 'task_run_partition', unique: false, element: ['u_run', 'u_partition_key'] },
        { name: 'task_cancel', unique: false, element: ['u_cancel_requested', 'u_state'] },
        { name: 'task_pool_lease_slot_unique', unique: true, element: 'u_pool_lease_slot' },
        { name: 'task_worker_lease_slot_unique', unique: true, element: 'u_worker_lease_slot' },
    ],
})

export const x_664635_topo_result = Table({
    accessibleFrom: 'package_private',
    callerAccess: 'restricted',
    allowWebServiceAccess: false,
    allowNewFields: false,
    allowUiActions: false,
    allowClientScripts: false,
    audit: true,
    extensible: false,
    textIndex: false,
    name: 'x_664635_topo_result',
    label: 'Topo Result Chunk',
    actions: ['read', 'delete'],
    schema: {
        u_task: ReferenceColumn({ label: 'Task', referenceTable: 'x_664635_topo_task', mandatory: true }),
        u_attempt_id: StringColumn({ label: 'Attempt ID', maxLength: 128, mandatory: true }),
        u_chunk_number: IntegerColumn({ label: 'Chunk number', mandatory: true }),
        u_chunk_count: IntegerColumn({ label: 'Chunk count', mandatory: true }),
        u_checksum: StringColumn({ label: 'Checksum', maxLength: 64, mandatory: true }),
        u_attachment: ReferenceColumn({ label: 'Attachment', referenceTable: 'sys_attachment' }),
        u_payload_bytes: IntegerColumn({ label: 'Payload bytes', mandatory: true }),
        u_processing_state: StringColumn({
            label: 'Processing state',
            maxLength: 40,
            mandatory: true,
            default: 'received',
            dropdown: 'dropdown_without_none',
            choices: {
                received: { label: 'Received' },
                processed: { label: 'Processed' },
                failed: { label: 'Failed' },
                superseded: { label: 'Superseded' },
            },
        }),
        u_terminal_outcome: StringColumn({
            label: 'Terminal outcome',
            maxLength: 40,
            dropdown: 'dropdown_with_none',
            choices: {
                complete: { label: 'Complete' },
                failed: { label: 'Failed' },
                cancelled: { label: 'Cancelled' },
                ambiguous: { label: 'Ambiguous' },
                superseded: { label: 'Superseded' },
            },
        }),
        u_processed_at: DateTimeColumn({ label: 'Processed at' }),
        u_delete_after: DateTimeColumn({ label: 'Delete after' }),
    },
    index: [
        { name: 'result_chunk_unique', unique: true, element: ['u_task', 'u_attempt_id', 'u_chunk_number'] },
        { name: 'result_retention', unique: false, element: ['u_processing_state', 'u_delete_after'] },
    ],
})

export const x_664635_topo_ire_delivery = Table({
    accessibleFrom: 'package_private',
    callerAccess: 'restricted',
    allowWebServiceAccess: false,
    allowNewFields: false,
    allowUiActions: false,
    allowClientScripts: false,
    audit: true,
    extensible: false,
    textIndex: false,
    name: 'x_664635_topo_ire_delivery',
    label: 'Topo IRE Delivery',
    display: 'u_idempotency_key',
    actions: ['read', 'delete'],
    schema: {
        u_idempotency_key: StringColumn({ label: 'Idempotency key', maxLength: 255, mandatory: true }),
        u_run: ReferenceColumn({ label: 'Run', referenceTable: 'x_664635_topo_run', mandatory: true }),
        u_task: ReferenceColumn({ label: 'Task', referenceTable: 'x_664635_topo_task', mandatory: true }),
        u_attempt_id: StringColumn({ label: 'Attempt ID', maxLength: 128, mandatory: true }),
        u_state: StringColumn({
            label: 'State',
            maxLength: 40,
            mandatory: true,
            default: 'preflight',
            dropdown: 'dropdown_without_none',
            choices: {
                preflight: { label: 'Preflight' },
                applied: { label: 'Applied' },
                no_data: { label: 'No supported data' },
                rejected: { label: 'Rejected' },
                ambiguous: { label: 'Ambiguous' },
            },
        }),
        u_items: IntegerColumn({ label: 'Items', mandatory: true, default: 0 }),
        u_relationships: IntegerColumn({ label: 'Relationships', mandatory: true, default: 0 }),
        u_diagnostics: StringColumn({ label: 'Diagnostics', maxLength: 4000 }),
        u_preflight_at: DateTimeColumn({ label: 'Preflight at' }),
        u_applied_at: DateTimeColumn({ label: 'Applied at' }),
    },
    index: [
        { name: 'ire_key_unique', unique: true, element: 'u_idempotency_key' },
        { name: 'ire_task_attempt_unique', unique: true, element: ['u_task', 'u_attempt_id'] },
        { name: 'ire_run_state', unique: false, element: ['u_run', 'u_state'] },
    ],
})
